### ISSUE TITLE
AsciiDoc "a" block-level table styling is not supported

### ISSUE THREAD

**Issue by owenh000** [owenh000/asciidoctor-multipage#1]
Asciidoctor supports block-level content in table cells with the AsciiDoc "a" attribute. See the [Asciidoctor User Manual](https://asciidoctor.org/docs/user-manual/#cols-style). It doesn't seem like a good idea, but it allows the writer to put things like lists and other such things in a single table cell.

It looks like Asciidoctor internally processes this type of cell as as a separate document. The multipage extension currently breaks when it encounters this new document.

**Comment by tajmone** [comment]
> It doesn't seem like a good idea, but it allows the writer to put things like lists and other such things in a single table cell.

It's actually an extremely useful feature; even in simple tables its use is often required to enforce certain styles or to bypass some bugs and quirks with Asciidoctor's native HTML template.

> It looks like Asciidoctor internally processes this type of cell as as a separate document.

Yes, and not without problems either. Advanced features have been problematic to handle (footnotes, Index entries, and other features relative to the global document), and a number of them have been buggy or inconsistent in their behaviour in the course of time. Various issues have been solved, but I'm not sure if it yet works 100% as expected.

> The multipage extension currently breaks when it encounters this new document.

Its lack of support in __asciidoctor-multipage__ is a major impediment in adopting this extension (along with no support for footnotes) for my projects, because in most documents where there are tables I end up using an `a` cell or column (even if just to fix some quirky behaviour of the native template); so I really hope you'll eventually find a way to fix the problem.

But it's probably going to be a problematic challenge, as mentioned above, because an `a` cell is effectively parsed as a sub-document of a kind, making it hard to trace references to the global document (notes, etc.). Also, since Asciidoctor supported nested tables, things could get rather ugly if you have an `a` cell in a nested table.

**Comment by owenh000** [comment]
Hi @tajmone, thanks for your comment. I agree it seems like a problematic feature, while I also agree it would be great for asciidoctor-multipage to support it if possible/practical since it is included in the Asciidoctor syntax. You're welcome to contribute some code or sponsor me here on GitHub if you'd like to see faster development (I too would like to have footnotes supported—issue #3).

**Comment by owenh000** [comment]
Thanks to @veselov for contributing a fix for this issue (<https://github.com/owenh000/asciidoctor-multipage/pull/14>).

If anyone notices any new problems related to nested documents, please open a new issue with details.

**Comment by tajmone** [comment]
Thanks @veselov! This was a major leap forward.
